FROM python:3.10-buster


# Install required system packages
RUN apt-get update && apt-get install -y \
   libgl1-mesa-glx \
   libglib2.0-0 \
   && rm -rf /var/lib/apt/lists/*


# Set working directory
WORKDIR /app


# Copy project files
COPY requirements.txt .
COPY app.py .
COPY best.pt .


# Install Python packages
RUN pip install --no-cache-dir -r requirements.txt


# Expose port 8080 for Cloud Run
EXPOSE 8080


# Command to run the app
CMD ["python", "app.py"]
